### ISSUE TITLE
could not make donation on Patreon: too expensive

### ISSUE THREAD

**Issue by maxadamo** [ReimuNotMoe/ydotool#117]
no wonder if you are not getting any support in Patreon. 
I wanted to make a donation, but the donation starts from 9 euro per month :smiley: 

1. by analogy, how much do I have to pay Linus Torvalds to use the Linux Kernel? Maybe 5 thousand euros per month? 
2. and how much do I have to pay to use Kubernetes? Maybe a thousand euros per month? 
3. 9 euros is what I pay every month to NetFlix. NetFlix movie quality is certainly arguable, but you can easily guess that Netflix, with thousand of people working, has a huge crystallization of labor compared to `ydotool` :smiley: 

Ultimately, why do you work with opensource if you don't seem to like it? 
I really understand your concern, about companies making money out of free tools, but can you imagine if we had to pay for every single tool running in the userspace of the UNIX systems? We should have to pay for tar, cp, rsync, rm, ssh, ls... These days are gone. In the 90's we were asked to pay to use WinZip :smile: 

There are other ways to protect your work: 

- never use BSD license (which allows companies to close your code). You are not using it, that's good. 
- use Patreon, and ask 50 cents per month for `ydotool` !  **50 cents per month is still too much, but we can decide to help you.**

**Comment by ClassicOldSong** [comment]
Pricing is compared to Vue.js on Patreon. What’s more, you’re supporting a
whole bunch of open source projects instead of just one.

Nevertheless, you could always use the software for free. It’s usable, but
if you want us to maintain it further more, or want us to make something
more fancy, we are not paid enough for it right now as a tiny startup who
isn’t getting any investment. Don’t forget that those tech giants are
making billions times of earning than us, even sparing a little bit out for
paying their employees to maintain those open source projects for “free”
won’t hurt them at all in financing, they could even make more earnings by
fitting these open source projects to their own needs.

We are not making a living by open source, while Linus doesn’t have the
need to thrive for survival in an abnormal employment environment. If you
consider it expensive in supporting us, you could help the project grow in
other ways like committing updates yourself, or just simply making more
people aware of it.

We will consider canceling sponsor programs if one day we could earn enough
that we think we can spare enough energy to maintain all these “for free”.
And, if we add a 50 cents option, it won’t make you appear on the
supporters list.

Remember, you have the right to fork this project or write a similar one by
yourself. We are not begging for your help.

**Comment by maxadamo** [comment]
in my defense, right now I tried to spread the word :angel: 
https://askubuntu.com/a/1372753/205255

**Comment by ClassicOldSong** [comment]
Thank you.

**Comment by chdslv** [comment]
Well, I suppose, if the developer(s) start saying "This project will not receive any updates from us unless there are supports." No one says that a developer shouldn't get paid, but those, who'd pay will be those, who are in need of the application. So, the idea is to make the application known and _**wanted**_.

**Comment by rmFlynn** [comment]
Just want to add, that I would pay you $0.5 to $2 US in a heart beat, especially if it was only for ydotool, or I would do a one off payment, but I can't do $10. If you lower the price, you will have 1000 sooner, I would think. Also, I don't need credit, I just need you to succeed until the world improves. Thanks!

**Comment by Nicceboy** [comment]
Just out of curiosity, don't you fix even serious bugs or security vulnerabilities without funding support? Because that means that the quality of the product will go downhill and makes me give second thoughts using this or even consider funding.

**Comment by ClassicOldSong** [comment]
You could always submit your pr if you find security issues that we may not
aware exists.

As the license says, we don’t actually have the responsibility to fix
things “for free”, otherwise it would be unwise to open source anything
since it will add tons responsibility to you out of the thin air.

But yeah, we could do necessary bug/security fixes, but we’re not a company
rich enough to maintain these for charity. So don’t expect us to have
updates frequently, or you can always help yourselves.

**Comment by chdslv** [comment]
Github is full of developers, who are _**not**_ a company. There are some, who specifically [say don't donate](https://github.com/pbatard/rufus). Certain applications are so needed and downloaded millions of times, while some are _**not that**_ wanted/needed. It is up to the developer to make his application wanted by people. Then, someone _**might**_ donate.

**Comment by Nicceboy** [comment]
> As the license says, we don’t actually have the responsibility to fix
things “for free”, otherwise it would be unwise to open source anything
since it will add tons responsibility to you out of the thin air.

I mean, at the moment you have one monthly regular payer, this changes as you ask money for instead of that being an option. What responsibilities you have for existing supporters?
Paying monthly usually means continuous support. For single payment it make sense to buy low bug fix or feature, but let's say I start paying monthly but there is risk that my money won't cover any serious bug fix. Why would I pay?

**Comment by ReimuNotMoe** [comment]
**Donate as you like.** No one is pointing a gun at your head and forcing you to donate, while others' decisions are not your concerns. To be honest I don't even understand the point of your questions. Are you showing concern to this project or being jealous about it? If I were you, having a lot time wandering on the Internet, I would rather spend my time with my family.

As the original author of this repo, if I continue to receive these useless arguments about the donating policy, I will start moderating the issues. If this costs me too much time rather than actually maintaining this project, I could consider deleting this repo and leave it to the community completely.

Choose wisely.

**Comment by chdslv** [comment]
> As the original author of this repo, if I continue to receive these useless arguments about the donating policy, I will start moderating the issues. If this costs me too much time rather than actually maintaining this project, I could consider deleting this repo and leave it to the community completely.
> 
> Choose wisely.
Blackmail, much?

**Comment by ClassicOldSong** [comment]
@Nicceboy It's unlikely that one single individual would be willing to pay full salary for a bug fix like a minor one for 20 bucks and a severe one for 200 bucks. Paying monthly with a relatively reasonable price (see my previous reply about where the pricing comes from) is to ensure the continuously development and maintainment of this project including minor and serious bug fixes, which is much more fair than one-shot paying.

We now do have supporters and we are planning to make an update on this project soon. Someone just don't understand how donations to open source projects should work. If this project isn't wanted by him, he shouldn't be here to argue about the price. On the other hand, if an open source project died for lacking of support, it won't even have a chance to be noticed to be needed or wanted.

**Comment by ClassicOldSong** [comment]
> Has anyone seen a fork of this?

@chdslv This project has merged nearly 40 pull requests and has 39 forks at the moment you reply with the above sentence.

I don't want to let those kind hearted contributors down for your inappropriate behavior.

**Comment by Nicceboy** [comment]
> We now do have supporters and we are planning to make an update on this project soon. Someone just don't understand how donations to open source projects should work. If this project isn't wanted by him, he shouldn't be here to argue about the price. On the other hand, if an open source project died for lacking of support, it won't even have a chance to be noticed to be needed or wanted.

I just wanted to understand the current situation, as the README gives strong emphasis with "It's simple: Pay for it or fork it." that gives impression that project is officially dead. It is a bit different from the situation where your normally give donations.

**Comment by ClassicOldSong** [comment]
@Nicceboy Yes it is. After we read about the mentioned story, we thought it's time for us to change the current unhealthy open source environment. We would like to encourage people to do the same for a more sustainable open source future.

**Comment by chdslv** [comment]
> > Has anyone seen a fork of this?
> 
> @chdslv This project has merged nearly 40 pull requests and has 39 forks at the moment you reply with the above sentence.
> 
In other words, there's no other fork. Let's see if anyone would fork this, that is, someone, who'd develop something for the sake of creating some useful service for others, that is, if anyone really needs it.

**Comment by ClassicOldSong** [comment]
> > > Has anyone seen a fork of this?
> 
> > 
> 
> > @chdslv This project has merged nearly 40 pull requests and has 39 forks at the moment you reply with the above sentence.
> 
> > 
> 
> In other words, there's no other fork. Let's see if anyone would fork this, that is, someone, who'd develop something for the sake of creating some useful service for others, that is, if anyone really needs it.
> 
> 
> 
> 

Just search ydotool on GitHub. You will be surprised.

Not going to talk to you anymore.

**Comment by chdslv** [comment]
> Just search ydotool on GitHub. You will be surprised.
> 
> Not going to talk to you anymore.

There's none, except yours...tells something, doesn't it?

**Comment by ReimuNotMoe** [comment]
Saved this thread to multiple Internet archives.

I'm not afraid of cyber violence at all.

**Comment by chdslv** [comment]
> Saved this thread to multiple Internet archives.
> 
> I'm not afraid of cyber violence at all.

Have a good day!

**Comment by Xorcerer** [comment]
My key takeaway is that, if you want more donations, it would be wise to lower the threshold of donation.

**Comment by ClassicOldSong** [comment]
@Xorcerer I think we've made it super clear: donate as you like. If you feel expensive, simply turn away and not making any donation and you'll still enjoying this project which is made live by others who choose to donate.

**Comment by ClassicOldSong** [comment]
@Xorcerer To be clear again, this has nothing to do with moral pressures for you to donate at a high price. By making the entrence high, we may can avaoid situations like Fakercloud being abused by Retool.

Thanks for your concern for this project, and yet again, if you feel expensive, you could help the project grow with other methods like contributing to the code or making more people know about it.

**Comment by user18130814200115-2** [comment]
The way I see it,
- You want money
- People want to give you money
- You do not let people give you money

I don't mean to be insulting here, as I understand the argument that people feel like they deserve their issues to be fixed after giving an incredibly small donation, but wouldn't this be better address with a clear and binding donation agreement?
Something that states: "by donating you are not entitled to anything whatsoever" and link to appropriate resources?

This way the project can get more funding,
the donators can be happier having more control over their spending, and overall, it would seem to me,
the environment would be less toxic.

**Comment by ClassicOldSong** [comment]
> I don't mean to be insulting here, as I understand the argument that people feel like they deserve their issues to be fixed after giving an incredibly small donation, but wouldn't this be better address with a clear and binding donation agreement?
> 
> Something that states: "by donating you are not entitled to anything whatsoever" and link to appropriate resources?
> 
> 

@user18130814200115-2 

That's a reasonable solution. Thanks for the advice.

**Comment by dhan78** [comment]
as may posters noted, if you lower donation to ~$1/month, you'll see exponential increase in donations/supporters. 
as the utility/word-of-mouth grows, you can then adjust threshold higher. welcome to Capitalism.
