### ISSUE TITLE
(X)Wayland mousemove relative and absolute coord/pos resolving issues

### ISSUE THREAD

**Issue by adeliktas** [ReimuNotMoe/ydotool#164]
i just built and test the current version of feb-2022 (1.0.1)

**Display Setup 3-2-1, where 2 is the primary display and all have a resolution of 1920x1080**

# **Mousemove absolute Issues:**
What actually works: any value for x in (0...959) AND any value for y in (0...540)

## 1) - Y-coordinates positive values resolving issue.
the value of y can be 0...540, before it reaches the bottom of the screen, which is actually 1080 pixels
`# ydotool mousemove -a 123 540`
## 2) - X-coordinates positive values resolving issue.
the value of x can be 0...959, before it reaches the next screen (actually 1920 pixels)
`# ydotool mousemove -a 959 123`

### 3.2) it moves to the prior/next screen accordingly, but then gets the 2.1 issue even though it's supposed to be absolute coordinates.
`# ydotool mousemove -a -- -1100 123`

Example 1: called from (primary) Display  2 `# ydotool mousemove -a -- -1100 123`
expectation: mouse moves to (lef) Display  3
-> results in mouse being at x=0,y=123 on (primary) Display  2

Example 2: called from (right) Display  1 `# ydotool mousemove -a -- -1100 123`
expectation: mouse moves to (primary) Display  2
-> results in mouse being at around x=800, y=123 on (lef) Display  3

# **Mousemove relative Issues:**
## 1) for y value there is only a range of 0...770 possible before it is reaches the bottom of the screen (actually 1080 pixels)
`# ydotool mousemove -- 0 770`
## 2) for x value there is only a range of 0...1090 possible before it is reaches the next screen (actually 1920 pixels)
`# ydotool mousemove -- 1090 0`

**and also i did confirm all these issues exist in the the prior version of jan-2021 (0.2.0) with it's older syntax/arguments:**

gentoo 5.17.14 ; openrc-0.44.10
gnome-desktop-42.2
xwayland-22.1.3

**Comment by adeliktas** [comment]
i just noticed 960 is the half of 1920 and 540 the half of 1080, so as workaround you can use x/2 and y/2 ...

**Comment by JohnGebbie** [comment]
I think this is because ydotool uses a relative pointer device even for absolute positioning by just whipping it up into a corner whipping it down, and this is affected by mouse acceleration.

A while back in X11, I had success disabling the acceleration:  https://github.com/JohnGebbie/void-packages/blob/0548811f926d352165ed66950e748a4e4233b22d/srcpkgs/ydotool/files/50-ydotool.conf, but then I wrote [dotool](https://git.sr.ht/~geb/dotool) which shouldn't have this issue

**Comment by ClassicOldSong** [comment]
Since `ydotool` doesn't rely on any display manager, it has no way to determine the current mouse location. As mouse acceleration is done on the display manager layer, ydotool also has no way to tell them to disable the acceleration.

> but then I wrote [dotool](https://git.sr.ht/~geb/dotool) which shouldn't have this issue

I don't think any tool that utilize `uinput` could have this issue solved without actively tapping into display managers, which is not a goal for `ydotool` to achieve.
