### ISSUE TITLE
Stable Releases

### ISSUE THREAD

**Issue by shibumi** [ReimuNotMoe/ydotool#19]
Hi,
I am Arch Linux Trusted User and I would like to push your software to our official repositories.
If you are interested it would be glad if you could schedule stable releases for your software.
This would make packaging a lot easier. Thanks

**Comment by ReimuNotMoe** [comment]
Thanks. I'll do this in near future.

I think a complete code coverage should be done before submitting it to official repositories of distros.

**Comment by ReimuNotMoe** [comment]
Now I've set up a CI for automated builds.

However this can't be used for coverage testing since this program is emulating keyboard events, and most CI implementation are container based.

So, a VM with VT and screen is required for automated coverage tests. Currently the only way is to do it locally.

In my personal opinion, the code quality is moderate now. You could push it to the official repo if you feel good.

**Comment by SenchoPens** [comment]
Hi, can you please tag latest stable (or just passing CI) release? I am really missing some features (especially `ydotool key --down` and `--up`). Of course I can package some untagged version for personal use, but with new release I think it will be easier for me to push it to official or at least to user repository for others to enjoy latest ydotool too (I am a Nixos user).
