### ISSUE TITLE
Strange behavior with --delay

### ISSUE THREAD

**Issue by AbsurdlySuspicious** [ReimuNotMoe/ydotool#5]
(aur: ydotool-git v0.1.5.r4.ged1e20f-1)
I just provide the terminal output

```
% ydotool key a                                                                  
ydotool: Executing `key' at 0x7fff41c8eef8
argc = 2
argv[1] = a
a⏎
        
% ydotool key --delay 5 a                                                 
ydotool: Executing `key' at 0x7ffff9298f78
argc = 4
argv[1] = --delay
argv[2] = 5
argv[3] = a
Delay was set to 5 milliseconds.

% ydotool key --delay 100 a                                               
ydotool: Executing `key' at 0x7fff83835f08
argc = 4
argv[1] = --delay
argv[2] = 100
argv[3] = a
Delay was set to 64 milliseconds.
a⏎
    
% ydotool key --delay 15 a                                                
ydotool: Executing `key' at 0x7ffc64b01098
argc = 4
argv[1] = --delay
argv[2] = 15
argv[3] = a
Delay was set to f milliseconds.

% ydotool key --delay 10 a                                             
ydotool: Executing `key' at 0x7fffb7bc8818
argc = 4
argv[1] = --delay
argv[2] = 10
argv[3] = a
Delay was set to a milliseconds.

% ydotool key --delay 150 a                                               
ydotool: Executing `key' at 0x7fff6f31f728
argc = 4
argv[1] = --delay
argv[2] = 150
argv[3] = a
Delay was set to 96 milliseconds.
a⏎                                                                                       

```

Also as seen, in some cases keycodes aren't event sent

**Comment by ReimuNotMoe** [comment]
ydotool works differently from xdotool. xdotool sends X events directly to X server, while ydotool uses the uinput framework of Linux kernel to emulate an input device.

When ydotool runs and creates an virtual input device, it will take some time for your graphical environment (X11/Wayland) to recognize and enable the virtual input device.

So, if the delay was too short, the virtual input device may not got recognized & enabled by your graphical environment in time.

Currently there's no way to solve this problem since ydotool is a generic input automation tool and not tied to any particular graphical environment.

If you have any ideas about this, feel free to tell me.

**Comment by AbsurdlySuspicious** [comment]
@ReimuNotMoe i thought about something like turning this into daemon to not block calling apps and prevent accidental repeats i.e. ignore next called keypress until previous called press of the same key is not "released". But it's obviously too high level for this project. Anyway i get it, thank you

**Comment by ReimuNotMoe** [comment]
Wow. It‘s a good idea and not too difficult to implement. I'll work on this when I have time. Thanks.

**Comment by ReimuNotMoe** [comment]
This issue is solved now. It's in the `develop` branch, you can have a try now.

Run `ydotoold` first, and then run `ydotool`.

**Comment by ReekyMarko** [comment]
@ReimuNotMoe I can not see the `develop` branch. Is it possible that you set it as private or something?

**Comment by AbsurdlySuspicious** [comment]
@ReekyMarko it's merged to master already

**Comment by carnager** [comment]
xdotool's --delay option works as a delay between each character being typed. In ydotool it only adds a delay before starting a type sequence, but there is no delay between characters. Is this meant to be this way?
