### ISSUE TITLE
getmouselocation

### ISSUE THREAD

**Issue by simlevesque** [ReimuNotMoe/ydotool#7]
Hi ! is it possible to get the current mouse position in Wayland ? It would really help me make scripts.

I looked on Google but found no answer to my question.

Thanks in advance !

**Comment by ReimuNotMoe** [comment]
Since we are emulating an input device (and not tied to any graphical environment), there's no way to get the mouse location inside X11/Wayland.

Another approach is to grab the mouse, read its movement information by ourselves, and replay these on an emulated mouse. This will introduce extra latency (depending on kernel configuration, you can or can't feel it), and requires mouse speed acceleration to be disabled.

Do you think this is acceptable? If so, we can have a try.

**Comment by AbsurdlySuspicious** [comment]
@ReimuNotMoe maybe it'll be easier to just read input* devices and track mouse movements within ydotoold? This will require some calibration to make sure about initial pointer location tough, and information about display geometry will also be required, acquiring which is still pretty non-trivial with wayland afaik.
