### ISSUE TITLE
--clearmodifiers suppport?

### ISSUE THREAD

**Issue by gandalf3** [ReimuNotMoe/ydotool#81]
When calling ydotool from some script triggered by a keybinding, there will often be modifier keys being held while ydotool is running. xdotool has an option `--clearmodifiers`, which ensures that such held modifiers don't interfere with xdotool's key presses.

Would it be possible to get `--clearmodifiers` supported in ydotool as well?

**Comment by ReimuNotMoe** [comment]
It's now possible in the newest version (using command chaining). But I may still not have much time to investigate this...

**Comment by jdeut** [comment]
> It's now possible in the newest version (using command chaining). But I may still not have much time to investigate this...

Maybe you have an example which illustrates the emulation of `--clearmodifiers`?

I simply don't mange it right.

Intuitively i played around with the `--up` switch of `ydotool key`. Unfortunately modifier keys are not released if they are physically pressed.

**Comment by csdvrx** [comment]
> It's now possible in the newest version (using command chaining). But I may still not have much time to investigate this...

Command chaining has now been deprecated (in the README: "Command chaining and sleep are removed because this should be your shell's job"), so could you reconsider adding a clearmodifiers flag?

**Comment by ClassicOldSong** [comment]
Unfortunately this won't be possible if you have your physical keyboard stuck with any key...

Since ydotool uses uinput to emulate a new input device, it can't do anything to your already connected physical keyboard. That means if you pressed `shift` on your physical keyboard, ydotool won't be able to move your finger away from that key, and also won't be able to tell your OS that this keypress on your physical keyboard should be ignored(but all key events in X are delegated with X so xdotool can do this thing).

If you'd like to clear certain modifiers that was previously pressed by ydotool, simply use ydotool itself to send release commands those keys.

**Comment by LaptopDev** [comment]
> > It's now possible in the newest version (using command chaining). But I may still not have much time to investigate this...
> 
> Command chaining has now been deprecated (in the README: "Command chaining and sleep are removed because this should be your shell's job"), so could you reconsider adding a clearmodifiers flag?

I saw your post in hyprland issues and I think I am stuck because of this. Have you figured out how to get ydotool to work as an exec bind?

**Comment by negora** [comment]
Although this workaround doesn't solve the issue entirely, in my custom script I've added a small delay **before** invoking `ydotool` and at least I've enough time to release the physical keys before they interfere with the synthetic keys. Specifically, I'm using a delay of 0.2 s.

```bash
sleep 0.2
ydotool key 29:1 42:1 33:1 33:0 42:0 29:0
```

I hope this helps someone.

**Comment by guino** [comment]
I got here because I also wanted to clear modifiers from physical keyboard before sending keys with `ydotool` (which doesn't seem possible right now). As I didn't want to wait for a specific amount of time before sending keys, I came up with a way to execute `ydotool` immediately after the modifier key is released (in my case SUPER/WINDOWS key):

Required packages (all fairly small): `wev expect`

Simple example executed with key biding SUPER SHIFT + KEY:
```
#!/bin/bash

# Check target window/client exists
c=$(hyprctl clients | grep -c 'WINDOWTITLE')
if [ "$c" == "0" ]; then
  exit 0
fi

# Wait for super/windows key to be released
unbuffer wev -f wl_keyboard |& grep -om1 'key: 133; state: 0' | xargs killall wev >& /dev/null

# Try to focus target window (also verify it didn't close since start of script)
result=$(hyprctl dispatch focuswindow "title:WINDOWTITLE")
if [ "$result" == "ok" ]; then
  ydotool type -d0 TEXTTOTYPE
fi
```
Not required but highly recommended if you don't want the `wev` window to flash:
```
windowrule = float on, size 0 0, match:class ^(wev)$
```

The above is still a rig and it can be improved but it does work as fast as I can press and release the keys.
