### ISSUE TITLE
Since some recent changes, DESTDIR no longer seems to be properly recognized in cmake builds

### ISSUE THREAD

**Issue by ghost91-** [ReimuNotMoe/ydotool#94]
I just tried to build ydotool using the AUR package (git version, https://aur.archlinux.org/packages/ydotool-git/). This no longer seems to work correctly because apparently DESTDIR is no longer being recognized correctly. Using the cmake and make commands from that PKGBUILD (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ydotool-git) results in the following directory structure:
```
.
└── usr
    ├── include
    │   └── cxxopts.hpp
    └── lib
        └── cmake
            └── cxxopts
                ├── cxxopts-config-version.cmake
                ├── cxxopts-config.cmake
                └── cxxopts-targets.cmake
```
The compilation itself seems to work correctly, the binaries are created in the build folder.

Has the way to install to a specific directory changed? How to do it correctly now? Or is this an unintentional breakage?

**Comment by ReimuNotMoe** [comment]
I addressed the CMake changes in the updated readme. You can have a look.

Unfortunately, the AUR is not created by me and I don't know how it works. You could ask the author.

**Comment by Depau** [comment]
Hi,
AUR maintainer here. I updated the package, however I don't understand this change.

- PREFIX defaults to `/usr/local`
- DATAROOTDIR defaults to `PREFIX/share`
- Binaries go to BINDIR, defaulting to `PREFIX/bin`
- Libraries go to `LIBDIR`, with `LIBDIR` defaulting to `PREFIX/lib`
- Systemd units go to `LIBDIR/systemd/{system,user}`
- Manpages go to MANDIR, which defaults to  `DATAROOTDIR/man/manSECTION`
- + other paths like `SBINDIR` etc which do not apply to this project

Reference:
- https://www.gnu.org/prep/standards/html_node/Directory-Variables.html (authoritative, GNU)
- https://www.gnu.org/software/automake/manual/html_node/Standard-Directory-Variables.html (from Automake, more concise)

Is there any distro that does not follow the standard? AFAIK all distros do, Arch wants `PREFIX == /usr` and `LIBDIR == PREFIX/lib`.

I know Ubuntu/Debian do more complicated hierarchies, however if you set everything as mentioned above there are no problems, since Ubuntu/Debian maintainers can override whatever they s.

Packagers will only need to set DESTDIR in `make install`. Other distros or packaging methods can set PREFIX and/or LIBDIR to whatever they want. If some distro feels particularly special and wants to move stuff around, `mv` still works.

This change only needlessly increases maintenance burden on maintainers which will have to update the build scripts to add whatever file is missing. And for Arch this has happened a considerable amount of time, since I just realized you added manpages and I haven't shipped them for a long time, cause CMake never installed them. The same happened for the systemd unit.

Is there an actual reason why using is a development burden? It seems straightforward to me, and to many other CMake-based projects.

**Comment by ClassicOldSong** [comment]
> Hi,
> AUR maintainer here. I updated the package, however I don't understand this change.
> 
> * `PREFIX` defaults to `/usr/local`
> * `DATAROOTDIR` defaults to `PREFIX/share`
> * Binaries go to `BINDIR`, defaulting to `PREFIX/bin`
> * Libraries go to `LIBDIR`, with `LIBDIR` defaulting to `PREFIX/lib`
> * Systemd units go to `LIBDIR/systemd/{system,user}`
> * Manpages go to `MANDIR`, which defaults to  `DATAROOTDIR/man/manSECTION`
> * * other paths like `SBINDIR` etc which do not apply to this project
> 
> Reference:
> 
> * https://www.gnu.org/prep/standards/html_node/Directory-Variables.html (authoritative, GNU)
> * https://www.gnu.org/software/automake/manual/html_node/Standard-Directory-Variables.html (from Automake, more concise)
> 
> Is there any distro that does not follow the standard? AFAIK all distros do, Arch wants `PREFIX == /usr` and `LIBDIR == PREFIX/lib`.
> 
> I know Ubuntu/Debian do more complicated hierarchies, however if you set everything as mentioned above there are no problems, since Ubuntu/Debian maintainers can override whatever satisfies their OCDs.
> 
> Packagers will only need to set DESTDIR in `make install`. Other distros or packaging methods can set PREFIX and/or LIBDIR to whatever they want. If some distro feels particularly special and wants to move stuff around, `mv` still works.
> 
> This change only needlessly increases maintenance burden on maintainers which will have to update the build scripts to add whatever file is missing. And for Arch this has happened a considerable amount of time, since I just realized you added manpages and I haven't shipped them for a long time, cause CMake never installed them. The same happened for the systemd unit.
> 
> Is there an actual reason why providing install configurations is a development burden? It seems pretty straightforward and well-documented to me, and to many other CMake-based projects.

A [PR](https://github.com/ReimuNotMoe/ydotool/pull/96) adding back `make install` was already merged, perhaps you could continue your work on packaging.

**Comment by Depau** [comment]
It works correctly, thanks :)
